[profile.default]
src = "src"
out = "artifacts"
optimizer = true
optimizer_runs = 10000
cbor_metadata = true
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin-upgradeable/=node_modules/@openzeppelin-upgradeable/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/=node_modules/@uniswap/",
    "base64-sol/=node_modules/base64-sol/",
    "hardhat/=node_modules/hardhat/",
    "notional-solidity-sdk/=node_modules/notional-solidity-sdk/",
    "openzeppelin-contracts-V4/=node_modules/openzeppelin-contracts-V4/",
    "wrapped-fcash/=node_modules/wrapped-fcash/",
    "contracts/=src/contracts/",
    "external/=external/",
]

[etherscan]
unknown_chain = { key = "E4sv1z5OnLkdB2UiKunJcNflZomkSE8t", chain = 8453, url = "https://virtual.base.us-east.rpc.tenderly.co/5fee4d63-b513-4b40-ae48-05769614d3c9" }

[fmt]
sort_imports = true

[rpc_endpoints]
tenderly = "https://virtual.base.us-east.rpc.tenderly.co/499e90ce-0e20-47d7-b409-6375e6ac5f4f"
anvil = "http://localhost:8545"